apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: inventrack-prod
  labels:
    app.kubernetes.io/name: frontend
    app.kubernetes.io/part-of: inventrack
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: tu-usuario/inventrack-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
