apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: inventrack-prod
  labels:
    app.kubernetes.io/name: backend
    app.kubernetes.io/part-of: inventrack
    environment: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: tu-usuario/inventrack-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
              name: http
          envFrom:
            - configMapRef:
                name: inventrack-config
            - secretRef:
                name: inventrack-secrets
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
