apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: inventrack-prod
  labels:
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: inventrack
    environment: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
